/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package AWSS3App;

import S3.S3Builder;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        S3Builder s3 = new S3Builder();
        s3.listBuckets();
    }
}
