/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package AWSS3App;
import java.io.*;
import java.nio.file.Paths;
import java.sql.SQLOutput;
import java.util.ArrayList;
import java.util.List;
import java.util.Scanner;

import S3.S3Builder;
import software.amazon.awssdk.core.ResponseInputStream;
import software.amazon.awssdk.regions.util.HttpResourcesUtils;
import software.amazon.awssdk.services.s3.model.GetObjectResponse;

public class App {

    public static void main(String[] args) throws FileNotFoundException, IOException {
        // Change these properties to your existing S3 account
        String bucketName = "nikitas-first-bucket";
        String filePath = "";
        String fileName = "helloWorldFile.txt";
        String fileMessage = "Hello World V3";

        File file = App.createTxtFile(filePath+fileName, fileMessage);

        S3Builder s3 = new S3Builder();

//      LIST BUCKETS
        System.out.println("Your Buckets:\n");
        s3.listBuckets();
        System.out.println("\n\n");

//      UPLOAD OBJECT TO BUCKET
        s3.uploadObjectsToBucket(bucketName,file,fileName);

//      DOWNLOAD
        ResponseInputStream s3File = s3.downloadObject(bucketName,fileName);

        File downloadedFile = new File("downloadedFile.txt");
        downloadedFile.createNewFile();
        OutputStream outputStream = new FileOutputStream(downloadedFile);

        int singleLine = s3File.read();
        while(singleLine != -1){
            outputStream.write(singleLine);
            singleLine = s3File.read();
        }

//      DELETE
        System.out.println("Do you  want to delete " + fileName + "? Y/N\n");

        Scanner in = new Scanner(System.in);
        String answer = in.nextLine();
        boolean deleteFile = answer =="Yes"||answer.toCharArray()[0] == 'Y' ? true:false;

        System.out.println(answer);
        System.out.println(deleteFile);

        if(deleteFile){
            s3.deleteObject(bucketName,fileName);
            System.out.println("Right Away");
        } else{
            System.out.println("As you wish");
        }
    }

    public static File createTxtFile(String name,String message) throws IOException {
        File file = new File(name);
        file.createNewFile();

        OutputStream outputStream = new FileOutputStream(file);
        outputStream.write(message.getBytes());
        outputStream.close();

        return file;
    }

}
